"""Derivative supplement -- appendix material complementing Lean's
``attention_fderiv_eq_eml`` theorem.

For 10 primitives we compute:
  (a) the closed-form forward expression,
  (b) its derivative via ``sympy.diff`` (simplified),
  (c) LaTeX for both.

Outputs ``paper/derivatives_supplement.md`` and
``paper/derivatives_supplement.tex``.
"""
from __future__ import annotations

from pathlib import Path

import sympy as sp


def _entries():
    x = sp.Symbol("x", real=True)
    entries = []

    # 1. sigmoid
    sig = 1 / (1 + sp.exp(-x))
    entries.append(("sigmoid", x, sig, sp.simplify(sp.diff(sig, x))))

    # 2. tanh
    th = sp.tanh(x)
    entries.append(("tanh", x, th, sp.simplify(sp.diff(th, x))))

    # 3. softplus
    sp_f = sp.log(1 + sp.exp(x))
    entries.append(("softplus", x, sp_f, sp.simplify(sp.diff(sp_f, x))))

    # 4. GELU (tanh approx)
    gelu = sp.Rational(1, 2) * x * (1 + sp.tanh(
        sp.sqrt(2 / sp.pi) * (x + sp.Rational(4471, 100000) * x ** 3)))
    entries.append(("GELU (tanh approx)", x, gelu, sp.simplify(sp.diff(gelu, x))))

    # 5. softmax_i w.r.t. x_k (for finite n=3 so diff is tractable)
    n_fixed = 3
    xs = sp.symbols("x_0 x_1 x_2", real=True)
    denom = sum(sp.exp(xj) for xj in xs)
    i_idx = 0
    k_idx = 1
    softmax_i = sp.exp(xs[i_idx]) / denom
    d_soft = sp.simplify(sp.diff(softmax_i, xs[k_idx]))
    entries.append((f"softmax_{i_idx} / ∂x_{k_idx} (n={n_fixed})",
                    xs[k_idx], softmax_i, d_soft))

    # 6. log-softmax_i w.r.t. x_k (n=3)
    log_soft_i = xs[i_idx] - sp.log(denom)
    d_log_soft = sp.simplify(sp.diff(log_soft_i, xs[k_idx]))
    entries.append((f"log-softmax_{i_idx} / ∂x_{k_idx} (n={n_fixed})",
                    xs[k_idx], log_soft_i, d_log_soft))

    # 7. LayerNorm per-component (sample-level, with scalar mu, sigma^2)
    mu = sp.Symbol("mu", real=True)
    s2 = sp.Symbol("sigma^2", positive=True)
    eps = sp.Symbol("epsilon", positive=True)
    gamma = sp.Symbol("gamma", real=True)
    beta_p = sp.Symbol("beta", real=True)
    ln_expr = gamma * (x - mu) / sp.sqrt(s2 + eps) + beta_p
    entries.append(("LayerNorm(x)", x, ln_expr,
                    sp.simplify(sp.diff(ln_expr, x))))

    # 8. RMSNorm
    rms_expr = gamma * x / sp.sqrt(s2 + eps)
    entries.append(("RMSNorm(x)", x, rms_expr,
                    sp.simplify(sp.diff(rms_expr, x))))

    # 9. log-domain attention weight (n=3): log_w_i = x_i - LSE
    lse = sp.log(denom)
    log_w_i = xs[i_idx] - lse
    w_i = sp.exp(log_w_i)
    d_w = sp.simplify(sp.diff(w_i, xs[k_idx]))
    entries.append((f"log-domain attention weight w_{i_idx}, ∂/∂x_{k_idx}",
                    xs[k_idx], w_i, d_w))

    # 10. Adam step (single parameter), derivative wrt g
    theta, g = sp.symbols("theta g", real=True)
    m_prev, v_prev = sp.symbols("m_prev v_prev", real=True)
    beta1, beta2, eps_a, eta, t = sp.symbols(
        "beta_1 beta_2 epsilon eta t", positive=True
    )
    m = beta1 * m_prev + (1 - beta1) * g
    v = beta2 * v_prev + (1 - beta2) * g ** 2
    m_hat = m / (1 - sp.exp(t * sp.log(beta1)))
    v_hat = v / (1 - sp.exp(t * sp.log(beta2)))
    theta_new = theta - eta * m_hat / (sp.sqrt(v_hat) + eps_a)
    d_adam = sp.simplify(sp.diff(theta_new, g))
    entries.append(("Adam step (∂θ_new/∂g)", g, theta_new, d_adam))

    return entries


def main():
    out_md = Path("paper/derivatives_supplement.md")
    out_tex = Path("paper/derivatives_supplement.tex")
    out_md.parent.mkdir(parents=True, exist_ok=True)

    entries = _entries()

    md = [
        "# Derivative supplement",
        "",
        "Closed-form forward expressions and their derivatives, computed via "
        "SymPy. Appendix companion to Lean's `attention_fderiv_eq_eml`.",
        "",
    ]
    tex = [
        "% Auto-generated by eml_nn/sympy/derivative_supplement.py",
        "% Appendix: closed-form derivatives (supplement to "
        "attention_fderiv_eq_eml).",
        "\\begin{description}",
    ]

    for name, wrt, forward, derivative in entries:
        f_tex = sp.latex(forward)
        d_tex = sp.latex(derivative)
        md.append(f"## {name}")
        md.append("")
        md.append(f"Forward:  $f = {f_tex}$")
        md.append("")
        md.append(f"Derivative ($\\partial / \\partial {sp.latex(wrt)}$):  "
                  f"$f' = {d_tex}$")
        md.append("")
        tex.append(
            f"  \\item[\\textbf{{{name}}}] "
            f"$f = {f_tex}$;\\ "
            f"$\\displaystyle \\frac{{\\partial f}}{{\\partial {sp.latex(wrt)}}} = {d_tex}$"
        )

    tex.append("\\end{description}")
    out_md.write_text("\n".join(md) + "\n")
    out_tex.write_text("\n".join(tex) + "\n")

    print(f"[derivative_supplement] wrote {out_md} and {out_tex}; "
          f"{len(entries)} entries")


if __name__ == "__main__":
    main()
